spring.application.name=GestionDeAverias

# Configuración de Base de Datos compatible con Docker y Local
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/incidencias?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin_password}

server.servlet.session.cookie.same-site=strict
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Configuración adicional de Hibernate
spring.jpa.open-in-view=false
